#
# Makefile for development
#

PY_SRC_PATH=$(HOME)/projects/compbio/python

RASMUS_SRC_FILES = __init__ \
		   treelib \
		   util

VERSIONS = versions.txt

# all
all: includepy

# copy subset of python modules for packaging with plct
includepy: versions
	mkdir -p python/plct/deps/rasmus
	for mod in $(RASMUS_SRC_FILES); do \
		cp $(PY_SRC_PATH)/rasmus/$${mod}.py python/plct/deps/rasmus/$${mod}.py; \
	done

# copy versions
versions:
	touch $(VERSIONS)

	echo -ne "rasmus\t" > $(VERSIONS)
	cd $(PY_SRC_PATH)/rasmus; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

# clean
clean:
	rm versions.txt
	rm python/plct/*.pyc
	rm -r python/plct/deps

